[package]
name = "eu4save"
version = "0.4.5-pre"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2018"
exclude = ["/assets/*", "/fuzz/*"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/rakaly/eu4save.git"
description = "Ergonomically work with all EU4 saves (ironman and multiplayer)"
keywords = ["eu4", "ironman"]
categories = ["parsing"]

[features]
mmap = ['memmap']
serialize = []

[dependencies]
jomini = "0.13.1"
once_cell = "1"
zip = { version =  "0.5", default-features = false, features = ["deflate"] }
serde = { version = "1", features = ["derive"] }
memmap = { version = "0.7", optional = true }

[dev-dependencies]
attohttpc = "0.17"
paste = "1"
criterion = "0.3"
twoway = "0.2"

[[bench]]
name = "eu4save_bench"
harness = false

# We override the test profile so that our tests run in a tolerable time as
# some of the asset files are heavyweight and can take a significant amount of
# time. Here is some timing data recorded to run one test:
#
# cargo test                 0m15.037s
# cargo test (opt-level=3)   0m9.644s
# cargo test (+lto=thin)     0m0.907s
# cargo test --release       0m0.620s
[profile.test]
opt-level = 3
lto = "thin"
